#INPUTS


[LogstreamerInput]
log_directory = "/opt/var/log/"
file_match = 'messages'

[DockerEventInput]
type = "DockerEventInput"

[JiraSyslogTCP]
type = "TcpInput"
address = ":5565"

[JiraSyslogUDP]
type = "UdpInput"
address = ":5565"


#DECODERS

[es_payload]
type = "SandboxEncoder"
filename = "/heka/sandbox/lua/encoders/es_payload.lua"
    [es_payload.config]
    es_index_from_timestamp = true
    index = "%{Logger}-%{%Y.%m.%d}"
    type_name = "%{Type}-%{Hostname}"

[PayloadEncoder]
append_newlines = false


#ENCODERS


[ESLogstashV0Encoder]
es_index_from_timestamp = true
type_name = "%{Type}"


[ESJsonEncoder]
es_index_from_timestamp = true
type_name = "%{Type}"


#OUTPUTS


[LogOutput]
message_matcher = "TRUE"
encoder = "PayloadEncoder"

[ElasticSearchOutput]
message_matcher = "TRUE"
server = "http://localhost:9200"
encoder = "es_payload"


[DashboardOutput]
static_directory = "/heka/dasher"
working_directory = "/tmp/heka"
ticker_interval = 1
address = "http://localhost:4352"
