[LogstreamerInput]
log_directory = "/opt/var/log/"
file_match = 'messages'

[DockerEventInput]
type = "DockerEventInput"

[PayloadEncoder]
append_newlines = false

[LogOutput]
message_matcher = "TRUE"
encoder = "PayloadEncoder"
