elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - ./elasticsearch/data:/usr/share/elasticsearch/data

#logstash:
#  build: logstash/
#  command: logstash -f /etc/logstash/conf.d/logstash.conf
#  volumes:
#    - ./logstash/config:/etc/logstash/conf.d
#  ports:
#    - "5000:5000"
#    - "5001:5001"
#    - "5002:5002"
#    - "12201:12201/udp"
#  links:
#    - elasticsearch
kibana:
  image: kibana:latest
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch

heka:
  image: ianneub/heka:latest
  container_name: heka
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./heka/config.toml:/etc/heka/config.toml
  links:
    - elasticsearch
  ports:
    - "4352:4352"
    - "5565:5565"
  command: hekad -config /etc/heka/config.toml


#filebeat:
#  image: bargenson/filebeat
#  restart: unless-stopped
#  volumes:
#   - /var/run/docker.sock:/tmp/docker.sock
#  environment:
#   - LOGSTASH_HOST=localhost
#   - LOGSTASH_PORT=5044
#   - SHIPPER_NAME=filebeatShipper
